### ISSUE TITLE
chart labels are overlapped by graph

### ISSUE THREAD

**Issue by steve2507** [SpectrumBroad/xible#3]
For the three charts in the editor (cpu, mem & event loop delay), the y-axis labels are overlapped by the graph itself

**Comment by steve2507** [comment]
Caused by https://github.com/chartjs/Chart.js/issues/2808

**Comment by SergioCordova** [comment]
Any updates on this, I am having the same issue with radar charts where the fill covers the tick labels and it's hard to see the numbers.

![image](https://user-images.githubusercontent.com/29874726/28342139-1016f4ca-6bd4-11e7-88ae-831295dc6345.png)

**Comment by steve2507** [comment]
@SergioCordova; I see you already commented on the chartjs repo, where this belongs.
The issue identified here is just a reference to the actual https://github.com/chartjs/Chart.js/issues/2808.
