### ISSUE TITLE
Node version 14 not supported; ERR_INVALID_ARG_TYPE on xible.init()

### ISSUE THREAD

**Issue by will-hill** [SpectrumBroad/xible#85]
### When I try to install xible via Dockerfile...  

FROM ubuntu:20.10  
RUN apt-get update  
RUN apt-get install -y curl  
RUN curl -sL https://deb.nodesource.com/setup_current.x | bash -  
RUN apt-get install -y nodejs  
RUN npm install xible -g  
RUN xible server start  

### I get the follow errors when building this Docker image...

Step 6/7 : RUN npm install xible -g
 ---> Running in 1f6391a8f020

/usr/bin/xible -> /usr/lib/node_modules/xible/bin/xible.js
/usr/bin/xiblepm -> /usr/lib/node_modules/xible/bin/xiblepm.js

> core-js-pure@3.6.4 postinstall /usr/lib/node_modules/xible/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js-pure@3.6.5 postinstall /usr/lib/node_modules/xible/node_modules/xible-wrapper/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> nodemon@2.0.3 postinstall /usr/lib/node_modules/xible/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/xible/node_modules/xible-wrapper/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/xible/node_modules/xible-nodepack-filesystem/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/xible/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ xible@0.18.1
added 1448 packages from 625 contributors in 23.576s
Removing intermediate container 1f6391a8f020
 ---> d4a93245423a
Step 7/7 : RUN xible server start
 ---> Running in 4477f805a676
2020-07-11T01:46:26.919Z xible {
  node: '14.5.0',
  v8: '8.3.110.9-node.23',
  uv: '1.38.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '6',
  llhttp: '2.0.4',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
2020-07-11T01:46:26.921Z xible initWeb
2020-07-11T01:46:27.091Z xible:config loading "/root/.xible/config.json"
2020-07-11T01:46:27.091Z xible:config error reading "/root/.xible/config.json": Error: ENOENT: no such file or directory, open '/root/.xible/config.json'
2020-07-11T01:46:27.091Z xible:config creating "/root/.xible/config.json"
2020-07-11T01:46:27.116Z xible:config loading "/root/.xible/config.json"
2020-07-11T01:46:27.132Z xible init
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (6)
    at Object.writeFile (fs.js:1385:5)
    at Xible.writePidFile (/usr/lib/node_modules/xible/index.js:84:8)
    at Xible.init (/usr/lib/node_modules/xible/index.js:155:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
The command '/bin/sh -c xible server start' returned a non-zero code: 1

**Comment by steve2507** [comment]
It seems that node version 14 is not supported at the moment. Node version 13 does work. I'm looking into it, meanwhile you could use version 13 of Node in your docker.

**Comment by steve2507** [comment]
Issue has been fixed in release 0.19.0 which is available on NPM now. Thanks for reporting this!

**Comment by steve2507** [comment]
@will-hill Just an FYI; XIBLE can now be found on [docker hub](https://hub.docker.com/r/spectrumbroad/xible) and [installation instructions are available](https://xible.io/docs/installation#docker).

There is still some work to be done here. Notably: https://github.com/SpectrumBroad/xible/issues/94
But it's working nonetheless!
