### ISSUE TITLE
Are you still continuing to support This project?

### ISSUE THREAD

**Issue by chansdad** [SpectrumBroad/xible#86]
Hello 

Are you still continuing to support this project? i see not much activity between 2018 and 2020 and just some new commits two months ago . 

I managed to get a simple flow of string concanate with console.log flow working.. I was looking for documentation on how i can see the same working via rest api .. http://localhost:9600/api/flows/Test/Instances where in it would display the concatenated "Hello Word" string. what nodepacks or nodes would i have to install ??  Any help would be greatly apprecaited.

Thanks

**Comment by steve2507** [comment]
I'm hoping to ramp up development again next year.

In the meanwhile to answer your questions on building flows;
For concatenating strings, the [string nodepack](https://xible.io/nodes?search=string) is required, but it should be there by default.
For exposing a REST api, you can use the [http nodepack](https://xible.io/nodes?search=http). I have a [video online](https://youtu.be/TbW-t3kFlnI?t=186) that demonstrates how to use it.

Let me know if that helps.

**Comment by chansdad** [comment]
Thanks , it helps . Question - So is a new http server being spawned on the port you specify for the flow, so you have demonstrated the /hello running on port 8080.  if i where to have another endpoint  like /todo , then do i have to add the http server again and specific a different port?

Thanks

**Comment by steve2507** [comment]
You can connect multiple inputs (and thus multiple nodes) to the same output. So in this case, you can relate multiple `http.server.on-request` nodes to a single `http.server` node.
When you double click the 'servers' output on the `http.server` node, it will automatically connect to all 'http.server' inputs within the flow, including `http.server.on-request`.

**Comment by steve2507** [comment]
Hi @chansdad; so I noticed there was a flaw while installing new version of xible.
As a result of this, it was not possible to load certain nodepacks. Those should be resolved now with the latest 0.19.2.
Feel free to upgrade and have a look!

**Comment by chansdad** [comment]
Thanks . Will look at it.
